"""
This type stub file was generated by pyright.
"""

HOME = ...
RESOURCES_PATH = ...

class ResourseGenerator:
    """"""

    def __init__(self, primary, secondary, disabled, source, parent=...) -> None:
        """Constructor"""
        ...
    def generate(self):  # -> None:
        """"""
        ...
    def replace_color(self, content, replace, color=...):
        """"""
        ...
