"""
This type stub file was generated by pyright.
"""

import base64
import logging
import os
import platform
import sys
from pathlib import Path
from xml.dom.minidom import parse

import jinja2
from PySide2.QtCore import QDir, Qt
from PySide2.QtGui import QColor, QFontDatabase, QGuiApplication, QPalette
from PySide2.QtUiTools import QUiLoader
from PySide2.QtWidgets import QAction, QActionGroup, QColorDialog
from PySide6.QtCore import QDir, Qt
from PySide6.QtGui import (
    QAction,
    QActionGroup,
    QColor,
    QFontDatabase,
    QGuiApplication,
    QPalette,
)
from PySide6.QtUiTools import QUiLoader
from PySide6.QtWidgets import QColorDialog
from qt_material.resources import RESOURCES_PATH, ResourseGenerator

GUI = ...
if "PySide2" in sys.modules: ...
else: ...
TEMPLATE_FILE = ...

def export_theme(
    theme=..., qss=..., rcc=..., invert_secondary=..., extra=..., output=..., prefix=...
):
    """"""
    ...

def build_stylesheet(
    theme=..., invert_secondary=..., extra=..., parent=..., template=..., export=...
):
    """"""
    ...

def get_theme(theme_name, invert_secondary=...): ...
def add_fonts():  # -> None:
    """"""
    ...

def apply_stylesheet(
    app, theme=..., style=..., save_as=..., invert_secondary=..., extra=..., parent=...
):
    """"""
    ...

def opacity(theme, value=...):  # -> str:
    """"""
    ...

def density(
    value, density_scale, border=..., scale=..., density_interval=...
):  # -> str | float | Literal[0]:
    """"""
    ...

def set_icons_theme(theme, parent=...):  # -> None:
    """"""
    ...

def list_themes():  # -> list[str]:
    """"""
    ...

def deprecated(
    replace,
):  # -> (fn: Unknown) -> ((*args: Unknown, **kwargs: Unknown) -> None):
    """"""
    ...

class QtStyleTools:
    """"""

    extra_values = ...
    @deprecated("set_extra")
    def set_extra_colors(self, extra):  # -> None:
        """"""
        ...
    def set_extra(self, extra):  # -> None:
        """"""
        ...
    def add_menu_theme(self, parent, menu):
        """"""
        ...
    def add_menu_density(self, parent, menu):
        """"""
        ...
    def apply_stylesheet(
        self, parent, theme, invert_secondary=..., extra=..., callable_=...
    ):  # -> None:
        """"""
        ...
    def update_theme_event(self, parent):
        """"""
        ...
    def update_buttons(self):  # -> None:
        """"""
        ...
    def get_color(self, color):  # -> QColor:
        """"""
        ...
    def update_theme(self, parent):  # -> None:
        """"""
        ...
    def set_color(self, parent, button_):  # -> () -> None:
        """"""
        ...
    def show_dock_theme(self, parent):
        """"""
        ...

def get_hook_dirs(): ...
