name: Release

# Controls when the workflow will run
on:
    # Triggers the workflow on push or pull request events but only for the main branch
    push:
        tags:
        - "v*.*.*"

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

jobs:
    bundle:
        strategy:
            fail-fast: false
            matrix:
                python-version: ["3.11"]
                poetry-version: [1.3]
                os: [ubuntu-latest, macos-latest, windows-latest, macos-10.15]
        runs-on: ${{ matrix.os }}
        permissions:
            contents: write
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-python@v4
              with:
                  python-version: ${{ matrix.python-version }}

            - name: Install Poetry
              uses: abatilo/actions-poetry@v2.0.0
              with:
                  poetry-version: ${{ matrix.poetry-version }}

            - name: Install dependencies
              run: poetry install

            - name: Install the Just task runner
              uses: extractions/setup-just@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Bundle
              run: just bundle

            - name: Upload build artifacts
              uses: actions/upload-artifact@v3
              with:
                  name: ${{ matrix.os }}-${{ matrix.python-version }}
                  path: dist/

    release:
        needs: bundle
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - name: Download build artifacts
              uses: actions/download-artifact@v3
              with:
                  path: dist/

            - name: Upload to release
              uses: svenstaro/upload-release-action@v2
              with:
                  repo_token: ${{ secrets.GITHUB_TOKEN }}
                  file: dist/*
                  tag: ${{ github.ref }}
                  overwrite: true
                  file_glob: true
